### ISSUE TITLE
Dragonfly module fails to get connected to the cellular network

### ISSUE THREAD

**Issue by gggekov** [ARMmbed/mbed-os-example-cellular#75] opened 2018-05-31 15:09 UTC
I struggle to connect the Dragonfly module to the cellular network. I am trying both TCP and UDP sockets and on both occasions have the following output: 
```
mbed-os-example-cellular
Establishing connection
.....................................................................................................................................................

Couldn't connect: -3004, will retry
```

Here is my mbed_app.json file:
```
{
    "config": {
        "sock-type": "UDP",
        "modem_trace": {
            "help": "Turns AT command trace on/off from the cellular modem, defaults to off",
            "value": true
        },
        "sim-pin-code": {
            "help": "SIM PIN code",
            "value": 0
        },
        "apn": {
            "help": "The APN string to use for this SIM/network, set to 0 if none",
            "value": "\"comms365.o2.com\""
        },
        "username": {
            "help": "The user name string to use for this APN, set to zero if none",
            "value": "\"******\""
        },
        "password": {
            "help": "The password string to use for this APN, set to 0 if none",
            "value": "\"******\""
        },
        "trace-level": {
            "help": "Options are TRACE_LEVEL_ERROR,TRACE_LEVEL_WARN,TRACE_LEVEL_INFO,TRACE_LEVEL_DEBUG",
            "macro_name": "MBED_TRACE_MAX_LEVEL",
            "value": "TRACE_LEVEL_DEBUG"
        }
  },
    "target_overrides": {
        "*": {
            "target.features_add": ["LWIP", "COMMON_PAL"],
            "mbed-trace.enable": false,
            "lwip.ipv4-enabled": true,
            "lwip.ethernet-enabled": false,
            "lwip.ppp-enabled": true,
            "lwip.tcp-enabled": true,
            "platform.stdio-convert-newlines": true,
            "platform.stdio-baud-rate": 115200,
            "platform.default-serial-baud-rate": 115200,
            "platform.stdio-buffered-serial": true
        }
    }
}

```
In the json I compile I replace the * of username and password with the real values.  Also note that I have enabled trace debug and AT trace but don't get any debug information on the serial output.

I experience this problem with ARM compiler and in the online IDE. 

Do you have any suggestion what is wrong and how to fix it? 

Thank you and kind regards,
George

**Comment by ashok-rao** [comment] 2018-05-31 15:18
@hasnainvirk .. any thoughts?

**Comment by ciarmcom** [comment] 2018-05-31 15:51
ARM Internal Ref: IOTCELL-1037

**Comment by AriParkkila** [comment] 2018-06-01 06:52
Do you have SIM that requires PIN, such as

        "sim-pin-code": {
            "help": "SIM PIN code",
            "value": "1234"
        }

You need to enable trace flag to see more details:

        "mbed-trace.enable": true

You can see more AT debug prints when PR #69 is integrated.

**Comment by gggekov** [comment] 2018-06-01 08:20
Hi @AriParkkila 
Thank you for the comment. I attach the debug trace when I try to connect over TCP.
```
mbed-os-example-cellular
Establishing connection
[00000000ms][INFO][CELL]: CELLULAR_DEVICE: TELIT_HE910
[00000001ms][DBG ][CELL]: process_oob readable=0, pos=0, len=0
[00000001ms][DBG ][CELL]: process_oob exit
[00000002ms][INFO][CELL]: Init state, waiting 0 ms before POWER state)
[00000008ms][INFO][CELL]: Cellular state from Init to Power
[00000015ms][INFO][CELL]: cellular_status: Init ==> Power
[00000021ms][INFO][CELL]: Cellular power ON (timeout 1000 ms)
[00000328ms][INFO][CELL]: Cellular state from Power to Device ready
[00000328ms][INFO][CELL]: cellular_status: Power ==> Device ready
[00001330ms][WARN][CELL]: AT timeout
[00001330ms][DBG ][CELL]: consume_to_tag not found
[00001330ms][WARN][CELL]: AT stop tag not found
[00001351ms][WARN][CELL]: AT timeout
[00001351ms][DBG ][CELL]: consume_to_tag not found
[00001351ms][WARN][CELL]: AT stop tag not found
[00001352ms][DBG ][CELL]: Retry State Device ready, retry 1/10
[00001352ms][INFO][CELL]: Cellular event in 2 seconds
ATE0ATE0

#STN: 5,0600
[00004359ms][WARN][CELL]: AT timeout
[00004359ms][DBG ][CELL]: consume_to_tag not found
[00004359ms][WARN][CELL]: AT stop tag not found
[00004380ms][WARN][CELL]: AT timeout
[00004380ms][DBG ][CELL]: consume_to_tag not found
[00004380ms][WARN][CELL]: AT stop tag not found
[00004381ms][DBG ][CELL]: Retry State Device ready, retry 2/10
[00004381ms][INFO][CELL]: Cellular event in 4 seconds
ATE0ATE0
OK
AT+CMEE=1
OK
AT&K0;&C1;&D0
OK
[00008471ms][INFO][CELL]: Cellular device ready
AT+CGREG=2
OK
AT+CREG=2
OK
[00008540ms][INFO][CELL]: Cellular state from Device ready to SIM pin
[00008540ms][INFO][CELL]: cellular_status: Device ready ==> SIM pin
[00008541ms][INFO][CELL]: Sim state (timeout 1000 ms)
AT+CPIN?
+CPIN: READY

OK
[00008576ms][INFO][CELL]: SIM is ready
[00008576ms][INFO][CELL]: Cellular state from SIM pin to Registering network
[00008577ms][INFO][CELL]: cellular_status: SIM pin ==> Registering network
AT+CGREG?
+CGREG: 2,0

OK
[00008612ms][DBG ][CELL]: get_network_registration: type=1, status=0
AT+CREG?
+CREG: 2,2

OK
[00008648ms][DBG ][CELL]: get_network_registration: type=2, status=2
AT+COPS?
+COPS: 0

OK
[00008683ms][DBG ][CELL]: automatic registering mode: 0
[00008683ms][DBG ][CELL]: Retry State Registering network, retry 1/10
[00008684ms][INFO][CELL]: Cellular event in 2 seconds
AT+CGREG?
+CGREG: 2,0

OK
[00010700ms][DBG ][CELL]: get_network_registration: type=1, status=0
AT+CREG?
+CREG: 2,2

OK
[00010736ms][DBG ][CELL]: get_network_registration: type=2, status=2
AT+COPS?
+COPS: 0

OK
[00010771ms][DBG ][CELL]: automatic registering mode: 0
[00010772ms][DBG ][CELL]: Retry State Registering network, retry 2/10
[00010772ms][INFO][CELL]: Cellular event in 4 seconds
AT+CGREG?
+CGREG: 2,0

OK
[00014789ms][DBG ][CELL]: get_network_registration: type=1, status=0
AT+CREG?
+CREG: 2,2

OK
[00014825ms][DBG ][CELL]: get_network_registration: type=2, status=2
AT+COPS?
+COPS: 0

OK
[00014860ms][DBG ][CELL]: automatic registering mode: 0
[00014860ms][DBG ][CELL]: Retry State Registering network, retry 3/10
[00014861ms][INFO][CELL]: Cellular event in 8 seconds
[00017675ms][DBG ][CELL]: process_oob readable=1, pos=4, len=4

[00017679ms][DBG ][CELL]: urc_cgreg
+CGREG: 0

[00017679ms][WARN][CELL]: not registered
[00017680ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00017680ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
+CREG: 0
[00017690ms][DBG ][CELL]: urc_creg
[00017694ms][WARN][CELL]: not registered
[00017699ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00017706ms][DBG ][CELL]: process_oob exit
[00022674ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00022677ms][DBG ][CELL]: urc_creg
[00022677ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00022678ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00022683ms][DBG ][CELL]: process_oob exit
AT+CGREG?
+CGREG: 2,0

OK
[00022878ms][DBG ][CELL]: get_network_registration: type=1, status=0
AT+CREG?
+CREG: 2,2

OK
[00022914ms][DBG ][CELL]: get_network_registration: type=2, status=2
AT+COPS?
+COPS: 0

OK
[00022950ms][DBG ][CELL]: automatic registering mode: 0
[00022950ms][DBG ][CELL]: Retry State Registering network, retry 4/10
[00022951ms][INFO][CELL]: Cellular event in 16 seconds
[00028087ms][DBG ][CELL]: process_oob readable=1, pos=1, len=1

[00028090ms][DBG ][CELL]: urc_creg
+CREG: 0
[00028090ms][WARN][CELL]: not registered
[00028091ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00028091ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00028100ms][DBG ][CELL]: process_oob exit
[00033086ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00033090ms][DBG ][CELL]: urc_creg
[00033090ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00033091ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00033095ms][DBG ][CELL]: process_oob exit
AT+CGREG?
+CGREG: 2,0

OK
[00038967ms][DBG ][CELL]: get_network_registration: type=1, status=0
AT+CREG?
+CREG: 2,2

OK
[00039003ms][DBG ][CELL]: get_network_registration: type=2, status=2
AT+COPS?
+COPS: 0

OK
[00039039ms][DBG ][CELL]: automatic registering mode: 0
[00039039ms][DBG ][CELL]: Retry State Registering network, retry 5/10
[00039040ms][INFO][CELL]: Cellular event in 32 seconds
[00044079ms][DBG ][CELL]: process_oob readable=1, pos=4, len=4

+CREG: 0
[00044083ms][DBG ][CELL]: urc_creg
[00044083ms][WARN][CELL]: not registered
[00044083ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00044084ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00044093ms][DBG ][CELL]: process_oob exit
[00049079ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00049083ms][DBG ][CELL]: urc_creg
[00049083ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00049084ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00049088ms][DBG ][CELL]: process_oob exit
[00049276ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00049278ms][DBG ][CELL]: urc_creg
+CREG: 0
[00049278ms][WARN][CELL]: not registered
[00049279ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00049279ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00049289ms][DBG ][CELL]: process_oob exit
[00054275ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00054277ms][DBG ][CELL]: urc_creg
+CREG: 2
[00054277ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00054278ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00054284ms][DBG ][CELL]: process_oob exit
[00065269ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00065272ms][DBG ][CELL]: urc_creg
[00065272ms][WARN][CELL]: not registered
[00065273ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00065273ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00065283ms][DBG ][CELL]: process_oob exit
[00070268ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00070272ms][DBG ][CELL]: urc_creg
[00070272ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00070273ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00070277ms][DBG ][CELL]: process_oob exit
[00070466ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00070468ms][DBG ][CELL]: urc_creg
+CREG: 0
[00070468ms][WARN][CELL]: not registered
[00070469ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00070469ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00070479ms][DBG ][CELL]: process_oob exit
AT+CGREG?
+CGREG: 2,0

OK
[00071056ms][DBG ][CELL]: get_network_registration: type=1, status=0
AT+CREG?
+CREG: 2,0

OK
[00071092ms][DBG ][CELL]: get_network_registration: type=2, status=0
AT+COPS?
+COPS: 0

OK
[00071127ms][DBG ][CELL]: automatic registering mode: 0
[00071127ms][DBG ][CELL]: Retry State Registering network, retry 6/10
[00071128ms][INFO][CELL]: Cellular event in 64 seconds
[00075465ms][DBG ][CELL]: process_oob readable=1, pos=3, len=3

[00075468ms][DBG ][CELL]: urc_creg
+CREG: 2
[00075468ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00075469ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00075474ms][DBG ][CELL]: process_oob exit
[00075665ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00075668ms][DBG ][CELL]: urc_creg
+CREG: 0
[00075668ms][WARN][CELL]: not registered
[00075669ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00075669ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00075679ms][DBG ][CELL]: process_oob exit
[00080665ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00080667ms][DBG ][CELL]: urc_creg
+CREG: 2
[00080667ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00080668ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00080674ms][DBG ][CELL]: process_oob exit
[00091659ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00091662ms][DBG ][CELL]: urc_creg
+CREG: 0
[00091662ms][WARN][CELL]: not registered
[00091663ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00091663ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00091673ms][DBG ][CELL]: process_oob exit
[00096659ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00096663ms][DBG ][CELL]: urc_creg
[00096663ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00096664ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00096668ms][DBG ][CELL]: process_oob exit
[00096855ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00096859ms][DBG ][CELL]: urc_creg
[00096859ms][WARN][CELL]: not registered
[00096859ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00096860ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00096869ms][DBG ][CELL]: process_oob exit
[00101855ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00101858ms][DBG ][CELL]: urc_creg
+CREG: 2
[00101858ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00101859ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00101864ms][DBG ][CELL]: process_oob exit
[00102055ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00102059ms][DBG ][CELL]: urc_creg
[00102059ms][WARN][CELL]: not registered
[00102059ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00102060ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00102069ms][DBG ][CELL]: process_oob exit
[00107055ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00107058ms][DBG ][CELL]: urc_creg
[00107058ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00107059ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00107064ms][DBG ][CELL]: process_oob exit
[00107255ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00107259ms][DBG ][CELL]: urc_creg
[00107259ms][WARN][CELL]: not registered
[00107259ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00107260ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00107269ms][DBG ][CELL]: process_oob exit
[00112255ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00112258ms][DBG ][CELL]: urc_creg
[00112258ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00112259ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00112264ms][DBG ][CELL]: process_oob exit
[00123247ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00123251ms][DBG ][CELL]: urc_creg
[00123251ms][WARN][CELL]: not registered
[00123251ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00123252ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00123261ms][DBG ][CELL]: process_oob exit
[00128247ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00128250ms][DBG ][CELL]: urc_creg
+CREG: 2
[00128250ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00128251ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00128256ms][DBG ][CELL]: process_oob exit
[00128446ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00128449ms][DBG ][CELL]: urc_creg
[00128449ms][WARN][CELL]: not registered
[00128450ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00128450ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00128460ms][DBG ][CELL]: process_oob exit
[00133446ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00133448ms][DBG ][CELL]: urc_creg
+CREG: 2
[00133448ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00133449ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00133454ms][DBG ][CELL]: process_oob exit
[00133645ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00133649ms][DBG ][CELL]: urc_creg
[00133649ms][WARN][CELL]: not registered
[00133649ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00133650ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00133659ms][DBG ][CELL]: process_oob exit
AT+CGREG?
+CGREG: 2,0

OK
[00135144ms][DBG ][CELL]: get_network_registration: type=1, status=0
AT+CREG?
+CREG: 2,0

OK
[00135180ms][DBG ][CELL]: get_network_registration: type=2, status=0
AT+COPS?
+COPS: 0

OK
[00135216ms][DBG ][CELL]: automatic registering mode: 0
[00135216ms][DBG ][CELL]: Retry State Registering network, retry 7/10
[00135217ms][INFO][CELL]: Cellular event in 128 seconds
[00138645ms][DBG ][CELL]: process_oob readable=1, pos=8, len=8

+CREG: 2
[00138648ms][DBG ][CELL]: urc_creg
[00138648ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00138649ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00138654ms][DBG ][CELL]: process_oob exit
[00138846ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00138849ms][DBG ][CELL]: urc_creg
[00138849ms][WARN][CELL]: not registered
[00138849ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00138850ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00138860ms][DBG ][CELL]: process_oob exit
[00143846ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00143849ms][DBG ][CELL]: urc_creg
[00143849ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00143850ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00143855ms][DBG ][CELL]: process_oob exit
[00144286ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00144289ms][DBG ][CELL]: urc_creg
[00144289ms][WARN][CELL]: not registered
[00144290ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00144290ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00144300ms][DBG ][CELL]: process_oob exit
[00149286ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

[00149288ms][DBG ][CELL]: urc_creg
+CREG: 2
[00149288ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00149289ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00149295ms][DBG ][CELL]: process_oob exit
[00160276ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00160280ms][DBG ][CELL]: urc_creg
[00160280ms][WARN][CELL]: not registered
[00160281ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00160281ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00160290ms][DBG ][CELL]: process_oob exit
[00165276ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00165280ms][DBG ][CELL]: urc_creg
[00165280ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00165281ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00165285ms][DBG ][CELL]: process_oob exit
[00165476ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00165479ms][DBG ][CELL]: urc_creg
[00165479ms][WARN][CELL]: not registered
[00165480ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00165480ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00165490ms][DBG ][CELL]: process_oob exit
[00170476ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 2
[00170479ms][DBG ][CELL]: urc_creg
[00170479ms][DBG ][CELL]: stat: 2, lac: -1, cellID: -1, act: -1
[00170480ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 2, _state: Registering network
[00170485ms][DBG ][CELL]: process_oob exit
[00170676ms][DBG ][CELL]: process_oob readable=1, pos=0, len=0

+CREG: 0
[00170679ms][DBG ][CELL]: urc_creg
[00170679ms][WARN][CELL]: not registered
[00170680ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00170680ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00170690ms][DBG ][CELL]: process_oob exit
```
It looks like it fails to register to the cellular network. Do you have an idea what may the reason for that? 
Thank you,
George

**Comment by AriParkkila** [comment] 2018-06-01 12:39
The modem is searching for a new operator, but it can't find a suitable network to register. Could you check (from the operator) that the SIM has also GPRS enabled for a data network?

**Comment by gggekov** [comment] 2018-06-01 12:59
How can I do this check?
When I put the SIM into a mobile phone, it connects straight away to O2 network.

**Comment by AriParkkila** [comment] 2018-06-04 05:52
I guess that your phone should display 3G data connection icon when GPRS is active? You could also ask that from your SIM operator too.

One explanation could be that you have e.g. O2/comms365 4G SIM without 3G fallback? Because your phone most likely supports 4G, it can connect to 4G network. But Dragonfly has only 3G support so it can't connect to network because SIM has only 4G enabled.

**Comment by AriParkkila** [comment] 2018-06-05 05:21
@gggekov "The SIM card has working 4G connection"...  Your Dragonfly modem only supports 3G connection. Could you check that SIM card also have 3G connectivity?

**Comment by gggekov** [comment] 2018-06-08 08:39
Hi @AriParkkila 
I confirm the SIM card has 3G connection. 
Running the example on the `mbed-os-5.9.0-rc2` branch results in the same output as before. I am getting repeatedly the following message. 
```
+CREG: 0
[00126528ms][DBG ][CELL]: urc_creg
[00126528ms][WARN][CELL]: not registered
[00126529ms][DBG ][CELL]: stat: 0, lac: -1, cellID: -1, act: -1
[00126529ms][INFO][CELL]: FSM: network_callback called with event: 4098, intptr: 0, _state: Registering network
[00126539ms][DBG ][CELL]: process_oob exit
```

**Comment by AriParkkila** [comment] 2018-06-08 10:34
+CREG: 2 means that modem is searching for an GSM operator.
+CREG: 0 means that modem is **not** searching for an GSM operator.

It's fine that modem sends CREG: 0/2 notifications in a loop when the modem is trying to find a suitable network. The problem is that the log has no +CGREG notifications, which would indicate that modem tries to find also a 3G/GPRS network.

Can you insert the SIM in your phone and search for available networks to see that there is O2 network with 3G service. Then you could try to set your phone in 3G only mode (disable 4G) to see that your phone can connect to that 3G network.

**Comment by gggekov** [comment] 2018-06-08 11:01
Hi Ari,
Yes, I confirm you that when I insert the SIM card in a phone it connects to the O2 network and my phone has data. I've tried with two different SIM cards and I am getting the same error message.

**Comment by AriParkkila** [comment] 2018-06-08 11:14
@gggekov did you disable 4G on your phone?

**Comment by gggekov** [comment] 2018-06-08 13:00
Hi @AriParkkila 
I confirm you I have set network mode as 3G-only on my phone and I do have internet connection with the same SIM card I am using on the Dragonfly.
If no one knows who to fix this problem at the moment, probably you may enable it for the next release of MbedOS.

**Comment by AriParkkila** [comment] 2018-06-11 04:57
@gggekov can you use successfully any SW with that Dragonfly board + SIM combination? Could this issue be because of broken HW or old firmware?

**Comment by gggekov** [comment] 2018-06-11 08:19
Hello Ari,
The mbed-os-example-cellular is the only test I've done that is combining the Dragonfly board + SIM card.  Please let me know  if there is another example app I can try that combines SIM card + Dragonfly. The Dragonfly board itself is working fine. 
Kind regards,
George

**Comment by AriParkkila** [comment] 2018-06-11 11:35
Yes, it would be good to check if modem firmware could be updated.

You could also try https://github.com/ARMmbed/mbed-os-example-cellular/tree/mbed-os-5.6-oob, which has previously been verified to work with Dragonfly.

**Comment by SeppoTakalo** [comment] 2018-06-11 13:36
If this already works on one of the tester, close this one and continue debugging network related issues on other thread.
This problem sound more generic to Cellular APIs and networking, than this application.

**Comment by AriParkkila** [comment] 2018-06-18 07:52
@gggekov any updates to this issue?

Do you think we could close this Github issue as @SeppoTakalo suggested, and continue debugging in ARM Internal Ref: IOTCELL-1037.

**Closed** 2018-06-18 08:19 UTC
Labels: mirrored
